name = "edge-chat-demo"
compatibility_date = "2024-01-01"
send_metrics = false

# Changed from src/chat.mjs to point to Remix build output
main = "build/index.js"

# Workers Site configuration for static assets
[site]
bucket = "public"

[build]
command = "npm run build"
# Watch directories for changes during development
watch_dir = "app"

[durable_objects]
bindings = [
  { name = "rooms", class_name = "ChatRoom" },
  { name = "limiters", class_name = "RateLimiter" }
]

# Rules for static assets and HTML files
[[rules]]
type = "Data"
globs = ["**/*.html"]
fallthrough = false

# Durable Objects migrations
[[migrations]]
tag = "v1"
new_classes = ["ChatRoom", "RateLimiter"]

# Uncomment these when adding D1/R2/KV later
# [[ d1_databases ]]
# binding = "DB"
# database_name = "edge-chat-demo"
# database_id = ""

# [[ r2_buckets ]]
# binding = "ASSETS"
# bucket_name = "edge-chat-demo-assets"